apiVersion: batch/v1
kind: Job
metadata:
  name: kubernetes-troubleshoot
spec:
  template:
    spec:
      containers:
      - name: troubleshoot
        image: your-troubleshoot-image
        args:
        - /troubleshoot.sh
      restartPolicy: Never
